name: Azure Container Apps Build and Deploy



on:
  # push:
  #   branches:
  #     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: Bootstrap environment
        type: environment
        required: true
env:
  COMMIT_SHORT_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ env.COMMIT_SHORT_SHA }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV


      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src
          acrName: crthunebyinfrastructure
          containerAppName: ca-albumapi
          resourceGroup: rg-container-apps
          imageToBuild: crthunebyinfrastructure.azurecr.io/albumapi:${{ env.COMMIT_SHORT_SHA }}
